version: 2.1

jobs:
  build_deploy:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Installing AWS CLI
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
      - run:
          name: Install Angular CLI
          command: |
            npm install @angular/cli
      - run: cd ./travelapp-admin && npm install && npm run build
      - run: aws s3 sync dist/ s3://admin-travel-app

workflows:
  version: 2
  execute_bulk:
    jobs:
      - build_deploy
