version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - npm/build-with-cache:
          steps:
          - run:
              name: Install Angular CLI
              working_directory: service-deployer-frontend
              command: |
                npm install @angular/cli
          - run:
              name: The First Step
              command: |
                ng build --prod
        - run:
            name: Code Has Arrived
            command: |
              ls -al
              echo '^^^That should look familiar^^^'
        - run:
            name: Running in a Unique Container
            command: |
              node -v
